### ISSUE TITLE
error with onnxruntime

### ISSUE THREAD

**Issue by geraldstanje** [onnx/sklearn-onnx#1111]
hi,

- how to fix the following issue when trying to export python model to onnx? i see: ```Failed to load library 
libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file```

  - details:
```
nvidia-smi
Thu Jun 20 16:07:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |
| N/A   26C    P8               8W /  70W |      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

root@fdd2e200ddd1:/workspace# find / -name "libcublasLt.so.11"
root@fdd2e200ddd1:/workspace# find / -name "libcublasLt.so"
/usr/local/cuda-12.3/targets/x86_64-linux/lib/stubs/libcublasLt.so
/usr/local/cuda-12.3/targets/x86_64-linux/lib/libcublasLt.so

find / -name "libonnxruntime_providers_cuda.so"
/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so
/opt/tritonserver/backends/onnxruntime/libonnxruntime_providers_cuda.so

2024-06-20 16:01:03.906843992 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] 
/onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& 
onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library 
libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory
```

- are the following warnings an issue?
  - warning1:
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.3.2 when using version 1.5.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

  - warning2:
24-06-20 17:00:09.916575384 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:870 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.

pip3 list:
```
onnx                     1.16.1
onnxconverter-common     1.14.0
onnxruntime-gpu          1.18.0
skl2onnx                 1.17.0
```

**Comment by xadupre** [comment]
It seems an error related to onnxruntime. Can you try ``import onnxruntime``? Can you add the version of numpy? onnxruntime does not support numpy 2.0 yet.

**Comment by geraldstanje** [comment]
i fixed it using: 
```
pip install onnxruntime-gpu==1.18.0 --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```

**Comment by xadupre** [comment]
I'll close the issue, Feel free to reopen it.
